# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Template for deploying a Sitex site to GitHub Pages
# Replace with your repository details as needed
name: Deploy Sitex to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18"
          otp-version: "27"

      - name: Install dependencies
        run: mix deps.get

      - name: Build static site
        run: mix sitex.build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ${{ secrets.GH_PAGES_REPO }}
          publish_dir: ./_site
